# Example configuration showing how to use the Dynamic Volume package
# with Home Assistant Voice PE

substitutions:
  name: your-ha-voice-device-name  # Replace with your device name
  friendly_name: Your HA Voice     # Replace with your friendly name

packages:
  # Official ESPHome Home Assistant Voice PE package
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
  # Dynamic Volume package
  Jaapp.DynamicVolume: github://jaapp/ha-voice-dynamic-volume/dynamic-volume.yaml

# Required base configuration
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

# Configure these with your own settings
api:
  encryption:
    key: YOUR_OWN_SUPER_SECRET_API_KEY

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password